# Generated by Django 5.0.1 on 2024-01-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('msg', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='HATApp.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='HATApp.person')),
            ],
        ),
    ]
