# Generated by Django 5.0.1 on 2024-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATApp', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(default='View', max_length=100),
        ),
    ]
