# Generated by Django 5.0.1 on 2024-04-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HATApp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attatchment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
