# Generated by Django 5.0.1 on 2024-04-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HATApp', '0005_message_attatchment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='attatchment',
            new_name='attachment',
        ),
    ]
